/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_finance_tradestrategy_utils_ToolMath */

#ifndef _Included_com_example_finance_tradestrategy_utils_ToolMath
#define _Included_com_example_finance_tradestrategy_utils_ToolMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_finance_tradestrategy_utils_ToolMath
 * Method:    isSegmentsIntersection
 * Signature: (FFFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_finance_tradestrategy_utils_ToolMath_isSegmentsIntersection
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);


JNIEXPORT jboolean JNICALL Java_com_example_finance_tradestrategy_utils_ToolMath_isLinesIntersect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

JNIEXPORT jobject JNICALL Java_com_example_finance_tradestrategy_utils_ToolMath_getSegmentsIntersection
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);
#ifdef __cplusplus
}
#endif
#endif
